<a href="https://colab.research.google.com/github/InscribeDeeper/bert_utils/blob/Jujun/conf_qa_similarity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import sys, os
# nb_path = '/content/rl'
# #os.symlink('/content/drive/MyDrive/Colab_Notebooks', nb_path)

# package_path = '/content/drive/MyDrive/Colab_Notebooks/packages'
# sys.path.insert(0,nb_path)
# sys.path.insert(0,package_path)

cur_path = os.path.join('/content/drive/MyDrive/Conf_Call/','Conf_Call')
print(os.getcwd())
os.chdir(cur_path)

/content


In [ ]:
import random, pickle
import numpy as np
import pandas as pd


In [ ]:
# Load the dataset into a pandas dataframe.

#data for merging yi and kiera
df = pd.read_csv("./code/5_emotion_extraction/merge_qa_label.csv", encoding="ISO-8859-1", index_col=0)


print(df.head())
# Report the number of sentences.
print('Number of training sentences: {:,}\n'.format(df.shape[0]))
df = df.drop(['Unnamed: 2'], axis=1)
# df = df.rename(columns={'merged':'label'})
# Display 10 random rows from the data.
df.sample(10)

                                            sentence Unnamed: 2  label
0  But I??m just wondering how you actually manag...        NaN      0
1  And how long did it took before they were at p...        NaN      0
2  It was interesting that you didn't call out cl...        NaN      1
3  What exactly is going on there that's allowing...        NaN      1
4                            What is going on there?        NaN      0
Number of training sentences: 1,173



sentence  label
243  How is that happening, with little variation o...      0
215  It is amazing to us how that maintenance CapEx...      0
882  Okay, so that is not kind of a slippery slope ...      1
856  And is it true that Ralph Polterman did the ta...      0
778  Just as you think about the growth in QuickBoo...      0
926  Has the structure of that program changed at a...      0
996  But Derek, when you were talking about the EET...      0
131  Is it kind of unexpected as they are related t...      1
72   So I was wondering what exactly was going on t...      0
142  I was impressed that even though you've had so...      1

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import pairwise_distances

In [ ]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(list(df.sentence))

In [ ]:
X

<1173x3041 sparse matrix of type '<class 'numpy.float64'>'
	with 20194 stored elements in Compressed Sparse Row format>

In [ ]:
S = 1 - pairwise_distances(X, metric="cosine")

In [ ]:
S

array([[1.        , 0.05727615, 0.01850899, ..., 0.0926722 , 0.04498216,
        0.02290986],
       [0.05727615, 1.        , 0.02603023, ..., 0.02114088, 0.05817856,
        0.00804566],
       [0.01850899, 0.02603023, 1.        , ..., 0.04234358, 0.06686829,
        0.03940899],
       ...,
       [0.0926722 , 0.02114088, 0.04234358, ..., 1.        , 0.09084942,
        0.05606477],
       [0.04498216, 0.05817856, 0.06686829, ..., 0.09084942, 1.        ,
        0.03044562],
       [0.02290986, 0.00804566, 0.03940899, ..., 0.05606477, 0.03044562,
        1.        ]])

In [ ]:
S.shape

(1173, 1173)

In [ ]:
S_1 = S.copy()
S_1 = S_1.astype(np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


In [ ]:
S_1

array([[1.        , 0.05727615, 0.01850899, ..., 0.0926722 , 0.04498216,
        0.02290986],
       [0.05727615, 1.        , 0.02603023, ..., 0.02114088, 0.05817856,
        0.00804566],
       [0.01850899, 0.02603023, 1.        , ..., 0.04234358, 0.06686829,
        0.03940899],
       ...,
       [0.0926722 , 0.02114088, 0.04234358, ..., 1.        , 0.09084942,
        0.05606477],
       [0.04498216, 0.05817856, 0.06686829, ..., 0.09084942, 1.        ,
        0.03044562],
       [0.02290986, 0.00804566, 0.03940899, ..., 0.05606477, 0.03044562,
        1.        ]])

In [ ]:
S_1.shape

(1173, 1173)

In [ ]:
np.fill_diagonal(S_1, -1)

In [ ]:
S_1

array([[-1.        ,  0.05727615,  0.01850899, ...,  0.0926722 ,
         0.04498216,  0.02290986],
       [ 0.05727615, -1.        ,  0.02603023, ...,  0.02114088,
         0.05817856,  0.00804566],
       [ 0.01850899,  0.02603023, -1.        , ...,  0.04234358,
         0.06686829,  0.03940899],
       ...,
       [ 0.0926722 ,  0.02114088,  0.04234358, ..., -1.        ,
         0.09084942,  0.05606477],
       [ 0.04498216,  0.05817856,  0.06686829, ...,  0.09084942,
        -1.        ,  0.03044562],
       [ 0.02290986,  0.00804566,  0.03940899, ...,  0.05606477,
         0.03044562, -1.        ]])

In [ ]:
a = np.where(S_1 > 0.6)

In [ ]:
a

(array([  4, 112, 117, 158, 207, 210, 323, 362, 362, 416]),
 array([158, 207, 210,   4, 112, 117, 362, 323, 416, 362]))

In [ ]:
for idx,i in enumerate(a[0][0:int(len(a[0])/2)]):
    print(i, a[1][idx])
    print(df.iloc[[i, a[1][idx]],:])
    print('**************')

4 158
                     sentence  label
4     What is going on there?      0
158  What was going on there?      0
**************
112 207
                         sentence  label
112  And what the timing on that?      0
207  What was the timing on that?      0
**************
117 210
                                            sentence  label
117                      I wasn't sure why that was.      0
210  I wasn??t sure why that was getting called out.      0
**************
158 4
                     sentence  label
158  What was going on there?      0
4     What is going on there?      0
**************
207 112
                         sentence  label
207  What was the timing on that?      0
112  And what the timing on that?      0
**************
